version: 1.0.{build}
before_build:
- ps: nuget restore ./Brandviser/Brandviser.sln
build:
  project: ./Brandviser/Brandviser.sln
  verbosity: minimal
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: 1LR3OaMdDrOFO3akXwxQuEwl0KKum8YI3CLx/CllTKdHn0k3o7guC2J3bvjowgqP
after_test: 
  - Brandviser\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"Brandviser\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single Brandviser\Brandviser.Tests\bin\Debug\Brandviser.Tests.dll" -output:cover.xml
  - Brandviser\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml