// <auto-generated />
namespace Brandviser.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201703151429483_Roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
